In [6]:
import pandas as pd
from sklearn.datasets import load_iris


In [7]:
iris=load_iris()

In [8]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [12]:
df=pd.DataFrame(data=iris.data,columns=iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [14]:
df["targets"]=iris.target

In [19]:
X=df.drop(["targets"],axis=1)

In [23]:
y=df["targets"]

In [33]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
import numpy as np

In [39]:
log=cross_val_score(LogisticRegression(solver="liblinear",multi_class="ovr"),X,y,cv=3)
log

array([0.96, 0.96, 0.94])

In [43]:
svm_=cross_val_score(SVC(),X,y,cv=3)

In [44]:
svm_

array([0.96, 0.98, 0.94])

In [49]:
RF=cross_val_score(RandomForestClassifier(n_estimators=70),X,y,cv=3)

In [50]:
RF

array([0.98, 0.94, 0.98])